workflows:
  sample-workflow:
    name: Codemagic Sample Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: origin/release_ViktorSoviak
          include: true
    scripts:
      - name: Test Echo
        script: echo "Test"
