workflows:
  sample-workflow:
    name: Codemagic Sample Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: release_ViktorSoviak
          include: true
    scripts:
      - name: Install rbenv and Ruby
        script: |
          brew install rbenv
          rbenv init
          echo 'eval "$(rbenv init -)"' >> ~/.zshrc
          source ~/.zshrc
          rbenv install 3.1.0
          rbenv global 3.1.0
          ruby -v
      - name: Install fastlane-plugin-firebase_app_distribution
        script: |
          gem install bundler
          gem install fastlane-plugin-firebase_app_distribution
      - name: Execute fastlane iOS publishing task
        script: |
          cd ios
          bundle install
          bundle exec fastlane build_and_export
    environment:
      groups:
        - firebase_credentials
        - google_credentials
