workflows:
  sample-workflow:
    name: Build and Export Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: release_ViktorSoviak
          include: true
    environment:
        groups:
            - firebase_credentials
        vars:
            XCODE_SCHEME: "CatsAndModules_ViktorSoviak"
            XCODE_WORKSPACE: "CatsAndModules_ViktorSoviak.xcworkspace"
    scripts:
        - name: Build ipa for distribution
          script: |
            xcodebuild archive \
            -archivePath $HOME/Library/Developer/Xcode/Archives/$XCODE_SCHEME.xcarchive \
            -workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Debug \
            -destination generic/platform=iOS

            xcodebuild -exportArchive \
            -archivePath $HOME/Library/Developer/Xcode/Archives/$XCODE_SCHEME.xcarchive \
            -exportPath $CM_BUILD_DIR/build/ios/ipa \
            -exportOptionsPlist $CM_BUILD_DIR/exportOptionsTemplate.plist
    publishing:
        firebase:
            # use this line to authenticate via service account
            firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
            ios:
                # Add your iOS app id retrieved from Firebase console
                app_id: 1:861168593205:ios:f9af2a363dcf92efd0847c

                # Add one or more groups that you wish to distribute your iOS application to.
                # You can create groups in the Firebase console
#                groups:
#                    - iosTesters
#                    - ...
