# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

before_all do
  xcode_select "/Applications/Xcode.app"
end

platform :ios do
  desc "Build, clean, archieve and export project to Firebase App Distribution"
  lane :build_and_export do
    increment_version_number(
      version_number: "1.1",    
      xcodeproj: "./CatsAndModules_ViktorSoviak/CatsAndModules_ViktorSoviak.xcodeproj"
    )
    # increment_build_number(
    #   build_number: 1.1,
    #   xcodeproj: "./CatsAndModules_ViktorSoviak/CatsAndModules_ViktorSoviak.xcodeproj"
    # )
      gym(export_method: "development")
    # add actions here: https://docs.fastlane.tools/actions

    # build_app(
    #   scheme: "CatsAndModules_ViktorSoviak",
    #   export_method: "development",
    #   export_options: {
    #     provisioningProfiles: {
    #       "ua.edu.ukma.apple-env.soviak.CatsAndModules-ViktorSoviak" => "04af43ad-f9c1-4416-af6a-87a22d2283bf"
    #     }
    #   }
    # )
    firebase_app_distribution(
      service_credentials_file: "./catsandmodules-viktorsov-b3523-6e5d61d7d5fc.json",
      ipa_path: "./output/CatsAndModules_ViktorSoviak.ipa",
      release_notes: "Fastlane, lab04_ViktorSovyak",
      testers: "o.frankiv@ukma.edu.ua"
      )
  end
end

platform :ios do
  desc "Take snapshots of MainScreen and DetailsView"
  lane :take_snapshots do
    snapshot
  end
end
